.TH queuedctl 1  "@CURRENT_DATE@" "version @PROJECT_VERSION@"
.SH NAME
Daemon for starting jobs to queue of calculation
.SH SYNOPSIS
.B queuedctl
[ options ] command
.SH DESCRIPTION
Daemon for starting jobs to queue of calculation. Client application to control
daemon
.SH COMMANDS
.IP auth
Gets new auth token
.IP option-get
Gets option value
.IP option-set
Sets option value
.IP perm-add
Sets user permission
.IP perm-remove
Removes user permission
.IP plugin-add
Adds plugin to load
.IP plugin-list
Shows enabled plugins
.IP plugin-remove
Removes plugin to load
.IP report
Shows usage report
.IP status
Server status
.IP task-add
Adds new task
.IP task-get
Gets task properties
.IP task-list
Gets tasks list
.IP task-set
Sets task properties
.IP task-start
Starts task
.IP task-stop
Stops task
.IP user-add
Adds new user
.IP user-get
Gets user properties
.IP user-list
Gets users list
.IP user-set
Sets user properties
.SH OPTIONS
.IP "--commands"
shows commands and descriptions
.IP "-d, --debug"
verbose output
.IP "-t, --token <token>"
path to file with cached token
.IP "-u, --user <user>"
username which will be used for actions
.IP "-v, --version"
show version and exit
.IP "-i, --info"
show build information and exit
.IP "-h, --help"
show this help and exit
.SH SEE ALSO
.BR queued-daemon (1)
.BR queued-server (1)
.SH AUTHOR
@PROJECT_AUTHOR@ <\fI@PROJECT_CONTACT@\fR>
.SH LICENSE
This software is licensed under @PROJECT_LICENSE@
