.TH queued.conf 5
.SH NAME
queued.conf - queued configuration file
.SH SYNOPSIS
/etc/queued.conf
.SH DESCRIPTION
This file configures various parameters of 
.BR queued (1).
.SH OPTIONS
.TP
.I WORKDIR=
Full path to directory with source jobs. Default is
.B /var/lib/queued/work.
This directory must contain source scripts
.B script-name
, a priority file (it is not necessary)
.B script-name.pr
and a file with username (it is not necessary too)
.B script-name.user.
.TP
.I JOBDIR=
Full path to directory with running jobs. Default is
.B /var/lib/queued/job.
All job files will be moved here.
.TP
.I QUEUEFILE=
Full path to file with queue list. Default is
.B /var/lib/queued/queue.
.TP
.I PRIORITY=
Default priority. Default is
.B 0.
The higher the value, the higher the priority of the task
.TP
.I SLEEPTIME=
Time interval in minutes. Default is
.B 5.
.TP
.I STARTASUSER=
Default user. Default is
.B root.
This user will own created files.
.SH SEE ALSO
.BR queued (1)
