.TH queued 1  "December 24, 2013" "version 1.2.0" "USER COMMANDS"
.SH NAME
queued - daemon for starting jobs to queue of calculations
.SH SYNOPSIS
.B queued
[ -c /etc/queued.conf ] [ -v | --version ] [ -h | --help ]
.SH DESCRIPTION
.B queued
is a simple daemon written on BASH for starting jobs to queue of calculations in the background.
.SH OPTIONS
.TP
-c /etc/queued.conf
Full path to configuration file. Default is 
.B /etc/queued.conf.
.TP
-h, --help
Show help and exit.
.TP
-v, --version
Show version and exit.
.SH FILES
.TP
/usr/lib/systemd/system/queued.service
Systemd service file.
.TP
/etc/queued.conf
Configuration file.
.SH EXAMPLES
.TP
# systemctl start queued.service
Start daemon with parameters that are described in configuration file.
.TP
# systemctl enable queued.service
Enable daemon autostart.
.SH USAGE WITH SYSTEMD
If you need change path to configuration file, copy standart service file to /etc directory:
.PP
.nf
# cp /usr/lib/systemd/system/queued.service /etc/systemd/system/queued-my-profile.service
.fi
.PP
Then replace path to configuration file to your option. For example,
.PP
.B from:
.nf
ExecStart=/usr/bin/queued
.fi
.B to
.nf
ExecStart=/usr/bin/queued -c /path/to/new/queued.conf
.fi
.PP
Copy configuration file and edit it:
.PP
.nf
# cp /etc/queued.conf /path/to/new/queued.conf
# $EDITOR /path/to/new/queued.conf
.fi
.PP
Then start service:
.PP
.nf
# systemctl start queued-my-profile.service
.fi
.SH ERRORS
Use
.B journalctl
to determine errors:
.nf
  [II] - information string
  [WW] - warning
  [EE] - error
.fi
.SH SEE ALSO
.BR add_queued (1)
.BR queued.conf (5)
.SH AUTHOR
Evgeniy Alexeev aka arcanis <\fIesalexeev@gmail.com\fR>
